# Generated by Django 5.2.5 on 2025-09-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('compared_with', models.TextField()),
                ('algorithm', models.CharField(default='TF-IDF', max_length=50)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_result', to='documents.submission')),
            ],
        ),
    ]
