# Generated by Django 5.2.5 on 2025-09-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismresult',
            name='report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plagiarismresult',
            name='compared_with',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plagiarismresult',
            name='similarity_score',
            field=models.FloatField(),
        ),
    ]
